### PR TITLE
Update to 1.12.2

### PR DESCRIPTION
**Pull request by zyojv**
A full update to 1.12.2

### CODE REVIEW

**Comment by ToMe25** [comment]
@TheUnderTaker11 Please... i want to use this mod on 1.12.2.

**Comment by TheUnderTaker11** [comment]
Thanks for commenting @ToMe25 , I don't even remember being notified about this originally, so my bad.

**Comment by TheUnderTaker11** [comment]
@Kronos9247 If you give me your curseforge name I will add you to the mod and allow you to upload this yoruself.

**Comment by ToMe25** [comment]
@Kronos9247 Please Upload a Build at [Curseforge](https://minecraft.curseforge.com/projects/more-avaritia).

**Pull request merged**
